export const SUGGESTED_PROMPTS = [
  'What does Frictionless Tracking mean?',
  'What integrations are planned?',
  'Who maintains this project?',
  'Is Focus Analytics available yet?',
  "What's the difference between a Project, Task, and Time Entry?",
  'What platforms does Worklog Studio support?',
  'Why did you build Worklog Studio?',
  "How is Worklog Studio different from tools like Toptal's Top Tracker or My Hours?",
  "What's on the roadmap?",
  'What features are you considering for the future?',
  'Is Worklog Studio free to use?',
  'Is my data stored locally or sent to a server?',
  "What's the app built with?",
  'How do I install it on Windows or Mac?',
  "I'm getting a security warning when I open the app — is that normal?",
  'What happens if the app crashes or I lose data?',
  'Can I contribute to the project?',
  "What's the license?",
];
